### ISSUE TITLE
Cannot Import It

### ISSUE THREAD

**Issue by Hartulino** [routerabfrage/badlion-src#1]
Hello, when I import it I get a lot of errors.

**Comment by bastianleicht** [comment]
Yes because it is not the complete Badlion file. I removed the Anti-Cheat. You can try to fix them and get it running but that is not the reason I uploaded it. Also, the Libraries are missing and it is all in all a mess! It is easier to decompile MCP and copy the features that you want in it. But therefore you need to know how to program in java!
